### ISSUE TITLE
XTAL not compiling

### ISSUE THREAD

**Issue by wrobeleczek** [Mikrocontroller-net/transistortester#13]
Project: mega328_color_kit
After enabling flag DWITH_XTAL and setting OP MHZ = 16 and WITH_SamplingADC = 1, compilation fails with error:
/usr/lib/gcc/avr/5.4.0/../../../avr/bin/ld: ../Obj/mega328_color_kit/mega328_color_kit.elf section `.text' will not fit in region `text'
/usr/lib/gcc/avr/5.4.0/../../../avr/bin/ld: region `text' overflowed by 1706 bytes

Would You like to tell me it is bug or I do someting wrong?

**Comment by kubi48** [comment]
Probably you use a too old avr-gcc compiler.

You can check your compiler version with the command:

avr-gcc -v

The compiler must optimize the code very well to fit this configuration (color-display).

Please make shure, that you use the avr-gcc with version 7.3.0 !

You can find this compiler at:

www.microchip.com/en-us/tools-resources/develop/microchip-studio/gcc-compilers

 

Best regards,

Karl-Heinz

 
 

Gesendet: Montag, 30. Oktober 2023 um 18:56 Uhr
Von: "wrobeleczek" ***@***.***>
An: "Mikrocontroller-net/transistortester" ***@***.***>
Cc: "Subscribed" ***@***.***>
Betreff: [Mikrocontroller-net/transistortester] XTAL not compiling (Issue #13)


 

Project: mega328_color_kit
After enabling flag DWITH_XTAL and setting OP MHZ = 16 and WITH_SamplingADC = 1, compilation fails with error:
/usr/lib/gcc/avr/5.4.0/../../../avr/bin/ld: ../Obj/mega328_color_kit/mega328_color_kit.elf section .text' will not fit in region text'
/usr/lib/gcc/avr/5.4.0/../../../avr/bin/ld: region `text' overflowed by 1706 bytes

Would You like to tell me it is bug or I do someting wrong?

**Comment by wrobeleczek** [comment]
Hi. 
Your advice is probably correct (my gcc version 5.4.0 (GCC)).
I downloaded toolchain-avr-master and tried compiled but my knowledge is poor, very poor (like my english, I'm very sorry).
Olny this:
**tools.bash
binutils.build.bash
gcc.build.bash
avr-libc.build.bash**
compiled OK without fail.
gdb.build.bash -> unfortunately not finished good.
I tried read informations of compilation and noticed:
1. checking for python2.7... no
configure: WARNING: python is missing or unusable; some features may be unavailable
but:
whereis python2.7
python2.7: /usr/bin/python2.7 /usr/lib/python2.7 /etc/python2.7 /usr/local/lib/python2.7 /usr/include/python2.7 /usr/share/man/man1/python2.7.1.gz
python2.7
Python 2.7.18 (default, Jul  1 2022, 10:30:50) 
[GCC 11.2.0] on linux2

2. hecking whether to use guile... guile-2.0
checking for pkg-config... /usr/bin/pkg-config
checking for usable guile from /usr/bin/pkg-config... configure: error: unable to find usable guile version from "guile-2.0"
make[1]: *** [Makefile:9610: configure-gdb] Fail 1
but:
whereis guile
guile: /usr/bin/guile /usr/lib/x86_64-linux-gnu/guile /usr/share/guile
GNU Guile 2.0.13
My OS is Linux Mint 21.2
Unfortunately, I can't cope with these problems. I don't even know if these errors caused the compilation to fail.

**Comment by Ho-Ro** [comment]
> Please make shure, that you use the avr-gcc with version 7.3.0 !

You can also use version `8.3.0` - see my [comparison of different versions](https://www.eevblog.com/forum/testgear/$20-lcr-esr-transistor-checker-project/msg5054215/#msg5054215).

Do not compile the toolchain on your own, `7.3.0` comes with the Arduino 1.x download for Linux and you can download the `8.3.0` binaries for Linux from
[ZakKemble's github](https://github.com/ZakKemble/avr-gcc-build/releases), especially from this link:
- [avr-gcc-8.3.0-x64-linux.tar.bz2](https://github.com/ZakKemble/avr-gcc-build/releases/download/v8.3.0-1/avr-gcc-8.3.0-x64-linux.tar.bz2)

You can also use the latest 13.2.0, it compiles much smaller again after the byte-hogs 9.x.y ... 12.x.y.
- [avr-gcc-13.2.0-1.fc38.x86_64.rpm](https://dl.fedoraproject.org/pub/fedora/linux/updates/38/Everything/x86_64/Packages/a/avr-gcc-13.2.0-1.fc38.x86_64.rpm)

I installed them locally for my user; I untarred the `8.3.0-*.tar.bz2` version and opened the `13.2.0-*.rpm` with the `mc` and copied the files into directories under my home dir, i.e. `~/.local/avr-gcc/avr-gcc-8.3.0` and `~/.local/avr-gcc/avr-gcc-13.2.0` and made softlinks from the avr-gcc binaries to `~/.local/bin/avr-gcc-8` and `~/.local/bin/avr-gcc-13`.

Then you can easily build with different version, just edit the `Makefile`.

HTH
Martin

**Comment by wrobeleczek** [comment]
Hi Martin.
Could you tell me exactly which avr-gcc binaries I can add softlinks to?

**Comment by kubi48** [comment]
I did unpack the avr8-gnu-toolchain-3.7.0.1796-linux.any.x86_64.tar.gz file

to my home directory ( /home/kub in my case).

After unpacking the avr-gcc is in /home/kub/avr8-gnu-toolchain-linux_x86_64/bin directory.

 

To replace the standard avr-gcc I have first removed the original compiler with:

sudo rm /usr/bin/avr-gcc

Don't worry about this remove because the same content is in /usr/bin/avr-gcc-5.4.0 .

 

Then I have installed a softlink to the new compiler:

sudo ln -s /home/kub/avr8-gnu-toolchain-linux_x86_64/bin/avr-gcc /usr/bin/avr-gcc

 

Of course, You must replace the /home/kub with your home directory name.

This trick works without problems.

 

Best regards,

Karl-Heinz

 

 
 

Gesendet: Dienstag, 31. Oktober 2023 um 18:03 Uhr
Von: "wrobeleczek" ***@***.***>
An: "Mikrocontroller-net/transistortester" ***@***.***>
Cc: "Karl-Heinz Kübbeler" ***@***.***>, "Comment" ***@***.***>
Betreff: Re: [Mikrocontroller-net/transistortester] XTAL not compiling (Issue #13)


 

Hi.
Your advice is probably correct (my gcc version 5.4.0 (GCC)).
I downloaded toolchain-avr-master and tried compiled but my knowledge is poor, very poor (like my english, I'm very sorry).
Olny this:
tools.bash
binutils.build.bash
gcc.build.bash
avr-libc.build.bash
compiled OK without fail.
gdb.build.bash -> unfortunately not finished good.
I tried read informations of compilation and noticed:


	
	checking for python2.7... no
	configure: WARNING: python is missing or unusable; some features may be unavailable
	but:
	whereis python2.7
	python2.7: /usr/bin/python2.7 /usr/lib/python2.7 /etc/python2.7 /usr/local/lib/python2.7 /usr/include/python2.7 /usr/share/man/man1/python2.7.1.gz
	python2.7
	Python 2.7.18 (default, Jul 1 2022, 10:30:50)
	[GCC 11.2.0] on linux2
	
	
	hecking whether to use guile... guile-2.0
	checking for pkg-config... /usr/bin/pkg-config
	checking for usable guile from /usr/bin/pkg-config... configure: error: unable to find usable guile version from "guile-2.0"
	make[1]: *** [Makefile:9610: configure-gdb] Fail 1
	but:
	whereis guile
	guile: /usr/bin/guile /usr/lib/x86_64-linux-gnu/guile /usr/share/guile
	GNU Guile 2.0.13
	My OS is Linux Mint 21.2
	Unfortunately, I can't cope with these problems. I don't even know if these errors caused the compilation to fail.

**Comment by Ho-Ro** [comment]
My $PATH looks like below (some parts removed for clarity), important is that `/home/horo/.local/bin` comes 1st. 
```
/home/horo/.local/bin: ... :/home/horo/bin:/bin:/usr/bin:/usr/local/bin: ...
```
So it is sufficient to put a link into this directory to override the global installed compiler, no need to delete something. Also you can use more than one version of the avr-gcc, this is the relevant content of `/home/horo/.local/bin`
```sh
~/.local/bin$ ls -l avr-*
lrwxrwxrwx 1 horo horo  9  4. Sep 09:05 avr-gcc -> avr-gcc-8
lrwxrwxrwx 1 horo horo 14  8. Sep 16:56 avr-gcc-12 -> avr-gcc-12.1.0
lrwxrwxrwx 1 horo horo 44 11. Sep 14:07 avr-gcc-12.1.0 -> ../avr-gcc/avr-gcc-12.1.0/bin/avr-gcc-12.1.0
lrwxrwxrwx 1 horo horo 14  9. Sep 15:49 avr-gcc-13 -> avr-gcc-13.2.0
lrwxrwxrwx 1 horo horo 44 11. Sep 14:08 avr-gcc-13.2.0 -> ../avr-gcc/avr-gcc-13.2.0/bin/avr-gcc-13.2.0
lrwxrwxrwx 1 horo horo 16  2. Sep 20:58 avr-gcc-5 -> /usr/bin/avr-gcc
lrwxrwxrwx 1 horo horo 13  2. Sep 20:57 avr-gcc-7 -> avr-gcc-7.3.0
lrwxrwxrwx 1 horo horo 72  2. Sep 20:55 avr-gcc-7.3.0 -> /home/horo/projects/Arduino/arduino/hardware/tools/avr/bin/avr-gcc-7.3.0
lrwxrwxrwx 1 horo horo 13  2. Sep 20:57 avr-gcc-8 -> avr-gcc-8.3.0
lrwxrwxrwx 1 horo horo 42 11. Sep 14:08 avr-gcc-8.3.0 -> ../avr-gcc/avr-gcc-8.3.0/bin/avr-gcc-8.3.0
lrwxrwxrwx 1 horo horo 18 12. Sep 10:40 avr-objcopy-13 -> avr-objcopy-13.2.0
lrwxrwxrwx 1 horo horo 41 12. Sep 10:54 avr-objcopy-13.2.0 -> ../avr-gcc/avr-gcc-13.2.0/bin/avr-objcopy
lrwxrwxrwx 1 horo horo 18 12. Sep 10:41 avr-objdump-13 -> avr-objdump-13.2.0
lrwxrwxrwx 1 horo horo 41 12. Sep 10:55 avr-objdump-13.2.0 -> ../avr-gcc/avr-gcc-13.2.0/bin/avr-objdump
lrwxrwxrwx 1 horo horo 15 12. Sep 10:54 avr-size-13 -> avr-size-13.2.0
lrwxrwxrwx 1 horo horo 38 12. Sep 10:55 avr-size-13.2.0 -> ../avr-gcc/avr-gcc-13.2.0/bin/avr-size
```

To use one specific version you have to modify the Makefile accordingly, in my case for the 1.50m version of the ComponenTester:
Change this part of the `Makefile`
```Makefile
# compiler flags
CC = avr-gcc
#CPP = avr-g++
OBJCOPY = avr-objcopy
OBJDUMP = avr-objdump
SIZE = avr-size
```
to 
```Makefile
# compiler flags
CC = avr-gcc-13
#CPP = avr-g++
OBJCOPY = avr-objcopy-13
OBJDUMP = avr-objdump-13
SIZE = avr-size-13
```
and use these variables below in the `Makefile`
```Makefile
#
#  link
#

# link firmware
$(NAME): ${OBJECTS}
	 ${CC} ${LDFLAGS} ${OBJECTS} ${LIBDIRS} ${LIBS} -o ${NAME}

# create hex file of firmware
%.hex: ${NAME}
	${OBJCOPY} -O ihex ${HEX_FLASH_FLAGS} $< $@

# create hex file of EEPROM data
%.eep: ${NAME}
	-${OBJCOPY} ${HEX_EEPROM_FLAGS} -O ihex $< $@ || exit 0

# create dump of firmware
%.lss: ${NAME}
	${OBJDUMP} -h -S $< > $@

# output firmware size and other info
size: ${NAME}
	@echo
	@{SIZE} -C --mcu=${MCU} $<


#
#  compile source files
#

# rule for all c-files
${OBJECTS_C}: %.o: %.c ${HEADERS} ${MAKEFILE_LIST}
	${CC} ${CFLAGS} -c ${@:.o=.c}

# rule for all S-files
${OBJECTS_S}: %.o: %.S ${HEADERS} ${MAKEFILE_LIST}
	${CC} ${CFLAGS} -c ${@:.o=.S}
```

**Comment by wrobeleczek** [comment]
Hi.
In my OS -> echo $PATH
/home/wrobel/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

~/.local/bin$ ls -l avr-*
-rwxr-xr-x 1 wrobel wrobel   569352 maj 11  2022 avr-addr2line
-rwxr-xr-x 1 wrobel wrobel   593248 maj 11  2022 avr-ar
-rwxr-xr-x 1 wrobel wrobel   778776 maj 11  2022 avr-as
-rwxr-xr-x 2 wrobel wrobel   920392 maj 11  2022 avr-c++
-rwxr-xr-x 1 wrobel wrobel   567896 maj 11  2022 avr-c++filt
-rwxr-xr-x 1 wrobel wrobel   916296 maj 11  2022 avr-cpp
-rwxr-xr-x 1 wrobel wrobel    24912 maj 11  2022 avr-elfedit
-rwxr-xr-x 2 wrobel wrobel   920392 maj 11  2022 avr-g++
-rwxr-xr-x 2 wrobel wrobel   916296 maj 11  2022 avr-gcc
-rwxr-xr-x 1 wrobel wrobel  1016712 sie 29 02:00 avr-gcc-13.2.0
-rwxr-xr-x 2 wrobel wrobel   916296 maj 11  2022 avr-gcc-7.3.0
-rwxr-xr-x 1 wrobel wrobel    23488 maj 11  2022 avr-gcc-ar
-rwxr-xr-x 1 wrobel wrobel    23456 maj 11  2022 avr-gcc-nm
-rwxr-xr-x 1 wrobel wrobel    23456 maj 11  2022 avr-gcc-ranlib
-rwxr-xr-x 1 wrobel wrobel   549608 maj 11  2022 avr-gcov
-rwxr-xr-x 1 wrobel wrobel   451488 maj 11  2022 avr-gcov-dump
-rwxr-xr-x 1 wrobel wrobel   475136 maj 11  2022 avr-gcov-tool
-rwxr-xr-x 1 wrobel wrobel  5148528 maj 11  2022 avr-gdb
-rwxr-xr-x 1 wrobel wrobel   623640 maj 11  2022 avr-gprof
-rwxr-xr-x 2 wrobel wrobel  1015096 maj 11  2022 avr-ld
-rwxr-xr-x 2 wrobel wrobel  1015096 maj 11  2022 avr-ld.bfd
-rwxr-xr-x 1 wrobel wrobel 23843136 sie 29 02:00 avr-lto-dump
-rwxr-xr-x 1 wrobel wrobel     1908 maj 11  2022 avr-man
-rwxr-xr-x 1 wrobel wrobel   581112 maj 11  2022 avr-nm
-rwxr-xr-x 1 wrobel wrobel   727512 maj 11  2022 avr-objcopy
-rwxr-xr-x 1 wrobel wrobel   836104 maj 11  2022 avr-objdump
-rwxr-xr-x 1 wrobel wrobel   593264 maj 11  2022 avr-ranlib
-rwxr-xr-x 1 wrobel wrobel   415736 maj 11  2022 avr-readelf
-rwxr-xr-x 1 wrobel wrobel   581688 maj 11  2022 avr-size
-rwxr-xr-x 1 wrobel wrobel   572296 maj 11  2022 avr-strings
-rwxr-xr-x 1 wrobel wrobel   727512 maj 11  2022 avr-strip

# compiler flags
CC = avr-gcc-13.2.0
###CPP = avr-g++
OBJCOPY = avr-objcopy-13
OBJDUMP = avr-objdump-13
SIZE = avr-size-13

After compilations:
~/transistortester-master/Software/trunk/mega328_color_kit$ make
rm -rf ../Obj/mega328_color_kit
mkdir -p ../Obj/mega328_color_kit
mkdir -p ../Obj/mega328_color_kit/dep
avr-gcc-13.2.0  -Wall -DWITH_MENU -DWITH_ROTARY_SWITCH=2 -DFOUR_LINE_LCD -DLCD_SCREEN_ROTATE=1 -DLCD_ST7565_H_FLIP=0 -DLCD_ST7565_H_OFFSET=0 -DLCD_ST7565_V_FLIP=1 -DLCD_CHANGE_COLOR=2 -DLCD_BG_COLOR=0x7800 -DLCD_FG_COLOR=0xffff -DLCD_ICON_COLOR=0x03ff -DFONT_8X16thin -DICON_TYPE=3 -DBIG_TP -DWITH_SELFTEST -DAUTO_CAL -DSHORT_UNCAL_MSG -DWITH_XTAL -DWITH_UJT -DWITH_PUT -DFET_Idss -DWITH_AUTO_REF -DREF_C_KORR=12 -DREF_L_KORR=40 -DC_H_KORR=0 -DWITH_VEXT -DRMETER_WITH_L -DCAP_EMPTY_LEVEL=4 -DAUTOSCALE_ADC -DREF_R_KORR=3 -DESR_ZERO=20 -DNO_AREF_CAP -DUSE_EEPROM -DPULLUP_DISABLE -DANZ_MESS=25 -DPOWER_OFF -DBAT_CHECK -DBAT_OUT=150 -DBAT_POOR=6400 -DBAT_NUMERATOR=133 -DBAT_DENOMINATOR=33 -mcall-prologues -I. -DLANG_POLISH -DLCD_ST_TYPE=7735 -DF_CPU=16000000UL -DF_CPU_HZ=16000000 -DMHZ_CPU=16 -mmcu=atmega328p -gdwarf-2 -std=gnu99 -Os -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -MD -MP -MT lcd_hw_4_bit.o -MF ../Obj/mega328_color_kit/dep/lcd_hw_4_bit.o.d  -ffunction-sections -fdata-sections -DSamplingADC -c -o ../Obj/mega328_color_kit/lcd_hw_4_bit.o ../lcd_hw_4_bit.S
../lcd_hw_4_bit.S:6:10: fatal error: avr/io.h: No such file or directory
    6 | #include <avr/io.h>
      |          ^~~~~~~~~~
compilation terminated.
make: *** [../finish.mk:14: ../Obj/mega328_color_kit/lcd_hw_4_bit.o] Fail 1

**Comment by Ho-Ro** [comment]
Do not *copy* or *hardlink* (`ln ...`) the binaries, you must create a softlink to the binaries, (`ln -s ../.../avr-gcc .`) because the `includes` are searched relative to the binaries. Compare your`.local/bin` and mine!

**Comment by wrobeleczek** [comment]
Hi.
Now, I understand my mistakes. 
The Compilation ends successful.
But when I send .hex to m328p have this:
avrdude -c usbasp -p m328p -U flash:w:mega328_color_kit.hex 
avrdude: warning: cannot set sck period. please check for usbasp firmware update.
avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.00s

avrdude: Device signature = 0x1e950f (probably m328p)
avrdude: NOTE: "flash" memory has been specified, an erase cycle will be performed
         To disable this feature, specify the -D option.
avrdude: erasing chip
avrdude: warning: cannot set sck period. please check for usbasp firmware update.
avrdude: reading input file "mega328_color_kit.hex"
avrdude: input file mega328_color_kit.hex auto detected as Intel Hex
avrdude: ERROR: address 0x8010 out of range at line 2049 of mega328_color_kit.hex
avrdude: read from file 'mega328_color_kit.hex' failed
avrdude: safemode: Fuses OK (E:FC, H:D9, L:F7)

avrdude done.  Thank you.

When I comment "XTAL" then I can send .hex, .eep without any error.
I noticed: 
**(without XTAL)**
16 MHz operation configured.
AVR Memory Usage
----------------
Device: atmega328p
Program:   31952 bytes (97.5% Full)
(.text + .data + .bootloader)
Data:        204 bytes (10.0% Full)
(.data + .bss + .noinit)
EEPROM:      890 bytes (86.9% Full)
(.eeprom)

**(whit XTAL)**
16 MHz operation configured.
AVR Memory Usage
----------------
Device: atmega328p
Program:   34416 bytes (105.0% Full)
(.text + .data + .bootloader)
Data:        212 bytes (10.4% Full)
(.data + .bss + .noinit)
EEPROM:      930 bytes (90.8% Full)
(.eeprom)

**Comment by Ho-Ro** [comment]
> The Compilation ends successful.

No!

> Program: 34416 bytes (105.0% Full)

Your resulting hex is too big for the processor- you should omit some other features.

**Comment by wrobeleczek** [comment]
What I meant was that the compilation finished correctly (without any previous errors).
So we're back to the beginning. 
Apparently, it remains to disable XTAL. :(
My features:
PROJECT = mega328_color_kit
CC = avr-gcc
OBJCOPY = avr-objcopy-13
OBJDUMP = avr-objdump-13
SIZE = avr-size-13
CFLAGS = -Wall
PARTNO = m328p
CFLAGS += -DWITH_MENU
CFLAGS += -DWITH_ROTARY_SWITCH=2
UI_LANGUAGE = LANG_ENGLISH
CFLAGS += -DFOUR_LINE_LCD
WITH_LCD_ST7565 = 7735
LCD_ST7565_RESISTOR_RATIO = 4
CFLAGS += -DLCD_SCREEN_ROTATE=1
CFLAGS += -DLCD_ST7565_H_FLIP=0
CFLAGS += -DLCD_ST7565_H_OFFSET=0
CFLAGS += -DLCD_ST7565_V_FLIP=1
CFLAGS += -DLCD_CHANGE_COLOR=2
CFLAGS += -DLCD_BG_COLOR=0x7800
CFLAGS += -DLCD_FG_COLOR=0xffff
CFLAGS += -DLCD_ICON_COLOR=0x03ff
CFLAGS += -DFONT_8X16thin
CFLAGS += -DICON_TYPE=3
CFLAGS += -DBIG_TP
CFLAGS += -DBIG_TP
CFLAGS += -DAUTO_CAL
CFLAGS += -DSHORT_UNCAL_MSG
WITH_SamplingADC = 1
CFLAGS += -DWITH_XTAL
CFLAGS += -DFET_Idss
CFLAGS += -DWITH_AUTO_REF
CFLAGS += -DREF_C_KORR=12
CFLAGS += -DREF_L_KORR=40
CFLAGS += -DC_H_KORR=0
CFLAGS += -DWITH_VEXT
CFLAGS += -DRMETER_WITH_L
CFLAGS += -DCAP_EMPTY_LEVEL=4
CFLAGS += -DAUTOSCALE_ADC
CFLAGS += -DREF_R_KORR=3
CFLAGS += -DESR_ZERO=20
CFLAGS += -DNO_AREF_CAP
OP_MHZ = 16
CFLAGS += -DUSE_EEPROM
CFLAGS += -DPULLUP_DISABLE
CFLAGS += -DANZ_MESS=25
CFLAGS += -DPOWER_OFF
CFLAGS += -DBAT_CHECK
CFLAGS += -DBAT_OUT=150
CFLAGS += -DBAT_POOR=6400
CFLAGS += -DBAT_NUMERATOR=133
CFLAGS += -DBAT_DENOMINATOR=33
INHIBIT_SLEEP_MODE = 0
PROGRAMMER=usbasp
BitClock=20
PORT=usb
PROGRAMMER=usbasp
include ../setup.mk
$(OBJDIR)/GetRLmultip.o: ../GetRLmultip.S $(MKFILES)
        $(CC) $(INCLUDES) $(CFLAGS) -c -o $@ $<

$(OBJDIR)/UfAusgabe.o: ../UfAusgabe.S $(MKFILES)
        $(CC) $(INCLUDES) $(CFLAGS) -c -o $@ $<

$(OBJDIR)/RvalOut.o: ../RvalOut.S $(MKFILES)
        $(CC) $(INCLUDES) $(CFLAGS) -c -o $@ $<

$(OBJDIR)/PinLayout.o: ../PinLayout.S $(MKFILES)
        $(CC) $(INCLUDES) $(CFLAGS) -c -o $@ $<

$(OBJDIR)/RefVoltage.o: ../RefVoltage.S $(MKFILES)
        $(CC) $(INCLUDES) $(CFLAGS) -c -o $@ $<

$(OBJDIR)/i2lcd.o: ../i2lcd.S $(MKFILES)
        $(CC) $(INCLUDES) $(CFLAGS) -c -o $@ $<

$(OBJDIR)/ReadADC.o: ../ReadADC.S $(MKFILES)
        $(CC) $(INCLUDES) $(CFLAGS) -c -o $@ $<

$(OBJDIR)/sleep_5ms.o: ../sleep_5ms.S $(MKFILES)
        $(CC) $(INCLUDES) $(CFLAGS) -c -o $@ $<

$(OBJDIR)/wait_for_key_ms.o: ../wait_for_key_ms.c $(MKFILES)
        $(CC) $(INCLUDES) $(CFLAGS) -c -o $@ $<

$(OBJDIR)/get_log.o: ../get_log.S $(MKFILES)
        $(CC) $(INCLUDES) $(CFLAGS) -c -o $@ $<

include ../finish.mk
$(NAME): ${OBJECTS}
         ${CC} ${LDFLAGS} ${OBJECTS} ${LIBDIRS} ${LIBS} -o ${NAME}

# create hex file of firmware
%.hex: ${NAME}
        ${OBJCOPY} -O ihex ${HEX_FLASH_FLAGS} $< $@

# create hex file of EEPROM data
%.eep: ${NAME}
        -${OBJCOPY} ${HEX_EEPROM_FLAGS} -O ihex $< $@ || exit 0

# create dump of firmware
%.lss: ${NAME}
        ${OBJDUMP} -h -S $< > $@
# rule for all c-files
${OBJECTS_C}: %.o: %.c ${HEADERS} ${MAKEFILE_LIST}
        ${CC} ${CFLAGS} -c ${@:.o=.c}

# rule for all S-files
${OBJECTS_S}: %.o: %.S ${HEADERS} ${MAKEFILE_LIST}
        ${CC} ${CFLAGS} -c ${@:.o=.S}

When I comment:
CFLAGS += -DWITH_UJT
CFLAGS += -DWITH_PUT
.....
AVR Memory Usage
----------------
Device: atmega328p
Program:   33786 bytes (103.1% Full) -> :(
(.text + .data + .bootloader)
Data:        212 bytes (10.4% Full)
(.data + .bss + .noinit)
EEPROM:      916 bytes (89.5% Full)
(.eeprom)
I don't know what else I can turn off. :(

**Comment by kubi48** [comment]
You can Try to remove other features, if you wish to enable XTAL testing with the color display.

I suggest:

CFLAGS += -DNO_TEST_T1_T7

#CFLAGS += -DFET_Idss


 

If you need the tests T1 to T7 for functional test (error case),

you must deselect the "CFLAGS += -DWITH_XTAL" to

enable the "CFLAGS += -DNO_TEST_T1_T7" .

 

Otherwise you can try to use a smaller font like:

CFLAGS += -DFONT_6X8
#CFLAGS += -DFONT_8X12thin

 

Best regards,

Karl-Heinz


 

 


Gesendet: Donnerstag, 02. November 2023 um 21:08 Uhr
Von: "wrobeleczek" ***@***.***>
An: "Mikrocontroller-net/transistortester" ***@***.***>
Cc: "Karl-Heinz Kübbeler" ***@***.***>, "Comment" ***@***.***>
Betreff: Re: [Mikrocontroller-net/transistortester] XTAL not compiling (Issue #13)


 

What I meant was that the compilation finished correctly (without any previous errors).
So we're back to the beginning.
Apparently, it remains to disable XTAL. :(
My features:
PROJECT = mega328_color_kit
CC = avr-gcc
OBJCOPY = avr-objcopy-13
OBJDUMP = avr-objdump-13
SIZE = avr-size-13
CFLAGS = -Wall
PARTNO = m328p
CFLAGS += -DWITH_MENU
CFLAGS += -DWITH_ROTARY_SWITCH=2
UI_LANGUAGE = LANG_ENGLISH
CFLAGS += -DFOUR_LINE_LCD
WITH_LCD_ST7565 = 7735
LCD_ST7565_RESISTOR_RATIO = 4
CFLAGS += -DLCD_SCREEN_ROTATE=1
CFLAGS += -DLCD_ST7565_H_FLIP=0
CFLAGS += -DLCD_ST7565_H_OFFSET=0
CFLAGS += -DLCD_ST7565_V_FLIP=1
CFLAGS += -DLCD_CHANGE_COLOR=2
CFLAGS += -DLCD_BG_COLOR=0x7800
CFLAGS += -DLCD_FG_COLOR=0xffff
CFLAGS += -DLCD_ICON_COLOR=0x03ff
CFLAGS += -DFONT_8X16thin
CFLAGS += -DICON_TYPE=3
CFLAGS += -DBIG_TP
CFLAGS += -DBIG_TP
CFLAGS += -DAUTO_CAL
CFLAGS += -DSHORT_UNCAL_MSG
WITH_SamplingADC = 1
CFLAGS += -DWITH_XTAL
CFLAGS += -DFET_Idss
CFLAGS += -DWITH_AUTO_REF
CFLAGS += -DREF_C_KORR=12
CFLAGS += -DREF_L_KORR=40
CFLAGS += -DC_H_KORR=0
CFLAGS += -DWITH_VEXT
CFLAGS += -DRMETER_WITH_L
CFLAGS += -DCAP_EMPTY_LEVEL=4
CFLAGS += -DAUTOSCALE_ADC
CFLAGS += -DREF_R_KORR=3
CFLAGS += -DESR_ZERO=20
CFLAGS += -DNO_AREF_CAP
OP_MHZ = 16
CFLAGS += -DUSE_EEPROM
CFLAGS += -DPULLUP_DISABLE
CFLAGS += -DANZ_MESS=25
CFLAGS += -DPOWER_OFF
CFLAGS += -DBAT_CHECK
CFLAGS += -DBAT_OUT=150
CFLAGS += -DBAT_POOR=6400
CFLAGS += -DBAT_NUMERATOR=133
CFLAGS += -DBAT_DENOMINATOR=33
INHIBIT_SLEEP_MODE = 0
PROGRAMMER=usbasp
BitClock=20
PORT=usb
PROGRAMMER=usbasp
include ../setup.mk
$(OBJDIR)/GetRLmultip.o: ../GetRLmultip.S $(MKFILES)
$(CC) $(INCLUDES) $(CFLAGS) -c -o $@ $<

$(OBJDIR)/UfAusgabe.o: ../UfAusgabe.S $(MKFILES)
$(CC) $(INCLUDES) $(CFLAGS) -c -o $@ $<

$(OBJDIR)/RvalOut.o: ../RvalOut.S $(MKFILES)
$(CC) $(INCLUDES) $(CFLAGS) -c -o $@ $<

$(OBJDIR)/PinLayout.o: ../PinLayout.S $(MKFILES)
$(CC) $(INCLUDES) $(CFLAGS) -c -o $@ $<

$(OBJDIR)/RefVoltage.o: ../RefVoltage.S $(MKFILES)
$(CC) $(INCLUDES) $(CFLAGS) -c -o $@ $<

$(OBJDIR)/i2lcd.o: ../i2lcd.S $(MKFILES)
$(CC) $(INCLUDES) $(CFLAGS) -c -o $@ $<

$(OBJDIR)/ReadADC.o: ../ReadADC.S $(MKFILES)
$(CC) $(INCLUDES) $(CFLAGS) -c -o $@ $<

$(OBJDIR)/sleep_5ms.o: ../sleep_5ms.S $(MKFILES)
$(CC) $(INCLUDES) $(CFLAGS) -c -o $@ $<

$(OBJDIR)/wait_for_key_ms.o: ../wait_for_key_ms.c $(MKFILES)
$(CC) $(INCLUDES) $(CFLAGS) -c -o $@ $<

$(OBJDIR)/get_log.o: ../get_log.S $(MKFILES)
$(CC) $(INCLUDES) $(CFLAGS) -c -o $@ $<

include ../finish.mk
$(NAME): ${OBJECTS}
${CC} ${LDFLAGS} ${OBJECTS} ${LIBDIRS} ${LIBS} -o ${NAME}

create hex file of firmware

%.hex: ${NAME}
${OBJCOPY} -O ihex ${HEX_FLASH_FLAGS} $&lt; $@

create hex file of EEPROM data

%.eep: ${NAME}
-${OBJCOPY} ${HEX_EEPROM_FLAGS} -O ihex $&lt; $@ || exit 0

create dump of firmware

%.lss: ${NAME}
${OBJDUMP} -h -S $&lt; > $@

rule for all c-files

${OBJECTS_C}: %.o: %.c ${HEADERS} ${MAKEFILE_LIST}
${CC} ${CFLAGS} -c ${@:.o=.c}

rule for all S-files

${OBJECTS_S}: %.o: %.S ${HEADERS} ${MAKEFILE_LIST}
${CC} ${CFLAGS} -c ${@:.o=.S}

When I comment:
CFLAGS += -DWITH_UJT
CFLAGS += -DWITH_PUT
.....
AVR Memory Usage

Device: atmega328p
Program: 33786 bytes (103.1% Full) -> :(
(.text + .data + .bootloader)
Data: 212 bytes (10.4% Full)
(.data + .bss + .noinit)
EEPROM: 916 bytes (89.5% Full)
(.eeprom)
I don't know what else I can turn off. :(

**Comment by wrobeleczek** [comment]
Hi Karl-Heinz.
I changed the font to 5x8 and... success!! :)
...
16 MHz operation configured.
AVR Memory Usage
----------------
Device: atmega328p
Program:   32692 bytes (99.8% Full)
(.text + .data + .bootloader)
Data:        212 bytes (10.4% Full)
(.data + .bss + .noinit)
EEPROM:      922 bytes (90.0% Full)
(.eeprom)

Thx for all. Very Thx.

**Comment by wrobeleczek** [comment]
Additionally, I noticed that avr-gcc-8.3.0 has a smaller .hex and .eep file than avr-gcc-7.3.0.
